version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SERVER_PORT: 8080
      LOG_FILE: /app/logs/latest.log
    volumes:
      -/logs/latest.log:/app/logs/latest.log:ro


  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

